[package]
name = "aleph-compiler"
version = "0.0.0"
authors = ["The Aleph.js authors"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
anyhow = "1.0.38"
base64 = "0.13.0"
indexmap = "1.6.1"
lazy_static = "1.4.0"
once_cell = "1.5.2"
path-slash = "0.1.4"
pathdiff = "0.2.0"
regex = "1.4.3"
relative-path = "1.3.2"
sha-1 = "0.9.3"
serde = { version = "1.0.123", features = ["derive"] }
url = "2.2.0"

# swc
# docs: https://swc.rs
swc_common = { version = "0.10.9", features = ["sourcemap"] }
swc_ecmascript = { version = "0.21.0", features = ["codegen", "parser", "react", "transforms", "visit"] }
swc_ecma_transforms_typescript = "0.5.0"
swc_ecma_transforms_compat = "0.5.0"
swc_ecma_transforms_proposal = "0.5.0"
swc_ecma_ast = "0.38.0"
swc_ecma_visit = "0.24.0"
swc_ecma_utils = "0.28.0"

# wasm-bindgen
# docs: https://rustwasm.github.io/docs/wasm-bindgen
wasm-bindgen = {version = "0.2.70", features = ["serde-serialize"]}
console_error_panic_hook = { version = "0.1.6", optional = true }

[profile.release]
# Tell `rustc` to optimize for speed and size
lto = true
